# -*- coding: utf-8 -*-
"""venkatesh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xv8oB3aHJLXk_LX1JcbDnUxEKV9JQbpi
"""

import pandas as pd

da=pd.read_excel('Input_1.xlsx')
da

"""here we have 12 rows and 56 columns where we have to break each row into multiple rows based on type of test.

creating a new dataframe which is required at final 
"""

data = pd.DataFrame(columns= ['Name',
                              'Username',
                              'Chapter Tag',
                              'Test_Name',
                              'answered',
                              'correct',
                              'score',
                              'skipped',
                              'Time_Taken',
                              'Wrong'])

"""initially making all column names as null and renaming into our convenient way"""

change = [0]*len(da.iloc[0,:])
change[3:len(da.iloc[0,:]):6] =["Concept Test 1","Concept Test 2","Concept Test 3","Concept Test 4","Topic Test 1","Concept Test 5","Topic Test 2","Full Test 1","Full test 2"]
print(change[3:56:6])

"""making new dataframe by breaking the each row and removing null value data at a time."""

for i in range(len(da.iloc[:])):
  for j in range(3,56,6):
    if da.iat[i,j] != '-':
      data.loc[len(data.index)] = [da.iat[i,0],da.iat[i,1],da.iat[i,2],change[j],da.iat[i,j+2],da.iat[i,j+3],da.iat[i,j],da.iat[i,j+5],da.iat[i,j+1],da.iat[i,j+4]]

final=data.set_index('Name')
final

download = pd.ExcelWriter('final.xlsx')
final.to_excel(download)
download.save()